import streamlit as st
from openai import OpenAI
import base64
import re
import io
import contextlib
import os
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# -------------------------------------------------------------------
# HELPER FUNCTIONS
# -------------------------------------------------------------------
def encode_image(uploaded_file):
    """Converts the uploaded Streamlit file into a base64 string."""
    return base64.b64encode(uploaded_file.getvalue()).decode('utf-8')

# -------------------------------------------------------------------
# SIDEBAR: Customization & Features
# -------------------------------------------------------------------
st.sidebar.title("⚙️ LLM Settings")

# 1. Select the Provider
provider = st.sidebar.selectbox(
    "Select Provider", 
    ["Gemini", "OpenAI", "Local (e.g., Ollama, LM Studio)"]
)

# 2. Set defaults based on the chosen provider
if provider == "Gemini":
    default_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
    default_model = "gemini-2.5-flash"
    default_key = os.getenv("API_KEY_GEMINI", "")
elif provider == "OpenAI":
    default_url = "https://api.openai.com/v1"
    default_model = "gpt-4o"
    default_key = os.getenv("API_KEY_OPENAI", "")
else:
    default_url = "http://localhost:11434/v1" 
    default_model = "llama3"
    default_key = ""

# 3. API Configuration
st.sidebar.subheader("API Configuration")
api_key = st.sidebar.text_input(
    f"{provider} API Key", 
    type="password", 
    value=default_key,
    help="Loaded automatically from .env if available."
)
base_url = st.sidebar.text_input("Base URL", value=default_url)
model_name = st.sidebar.text_input("Model Name", value=default_model)

# 4. Feature Toggles
st.sidebar.subheader("Advanced Features")
enable_sandbox = st.sidebar.checkbox(
    "🐍 Enable Python Sandbox", 
    value=False, 
    help="Automatically execute Python code blocks generated by the AI and feed the output back into memory."
)

# 5. System Prompt / Persona Selection
st.sidebar.subheader("System Prompt")

# Dictionary of preset personas
persona_options = {
    "Brilliant Researcher": "You are a brilliant researcher. You excel at explaining complex topics logically and accurately, particularly in technical fields like machine learning, probability, and advanced algorithms. You provide thorough, step-by-step analytical answers and write exceptionally clean code.",
    "Friend": "You are a close, supportive friend. You speak casually, use emojis, and are always down to chat about everyday life, anime, music, or a good board game. You are empathetic, warm, and genuinely fun to talk to.",
    "Mentor": "You are a wise and patient mentor. You don't just give away the answers; you guide the user to understand the underlying concepts themselves. You offer constructive feedback, structure your advice clearly, and encourage continuous growth.",
    "Custom (Type yourself)": ""
}

# Dropdown to select persona
selected_persona = st.sidebar.selectbox("Choose a Persona", list(persona_options.keys()))

# Text area updates based on selection, but remains editable
if selected_persona == "Custom (Type yourself)":
    system_prompt = st.sidebar.text_area("Define the AI's behavior:", value="You are a highly capable AI assistant.", height=150)
else:
    system_prompt = st.sidebar.text_area("System Prompt (You can still edit this):", value=persona_options[selected_persona], height=150)

# -------------------------------------------------------------------
# MAIN UI & SHORT-TERM MEMORY
# -------------------------------------------------------------------
st.title("My Personal LLM 🧠")

# Initialize memory in Streamlit's session state
if "messages" not in st.session_state:
    st.session_state.messages = []

if st.sidebar.button("Clear Chat History"):
    st.session_state.messages = []
    st.rerun()

# Render existing conversation (Handling both text and multimodal history)
for message in st.session_state.messages:
    if message["role"] == "system" and message["content"] != system_prompt:
        continue
        
    with st.chat_message(message["role"]):
        if isinstance(message["content"], str):
            st.markdown(message["content"])
        elif isinstance(message["content"], list):
            for item in message["content"]:
                if item["type"] == "text":
                    st.markdown(item["text"])
                elif item["type"] == "image_url":
                    st.caption("📎 [Image attached in memory]")

# -------------------------------------------------------------------
# VISION UPLOAD & CHAT INPUT
# -------------------------------------------------------------------
uploaded_image = st.file_uploader("Attach an image (Optional)", type=["jpg", "jpeg", "png"])

if prompt := st.chat_input("What's on your mind?"):
    
    with st.chat_message("user"):
        st.markdown(prompt)
        
        if uploaded_image:
            st.image(uploaded_image, caption="Uploaded Image", width=300)
            base64_img = encode_image(uploaded_image)
            mime_type = uploaded_image.type
            user_msg = {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:{mime_type};base64,{base64_img}"}
                    }
                ]
            }
        else:
            user_msg = {"role": "user", "content": prompt}

    st.session_state.messages.append(user_msg)

    with st.chat_message("assistant"):
        if not api_key and provider != "Local (e.g., Ollama, LM Studio)":
            st.warning(f"⚠️ Please enter your {provider} API Key.")
        else:
            try:
                client = OpenAI(api_key=api_key or "local-key-not-needed", base_url=base_url)
                
                # Ensure the current system prompt is always injected at the start
                api_messages = [{"role": "system", "content": system_prompt}] + st.session_state.messages

                stream = client.chat.completions.create(
                    model=model_name,
                    messages=api_messages,
                    stream=True, 
                )
                full_response = st.write_stream(stream)
                
                st.session_state.messages.append({"role": "assistant", "content": full_response})

                if enable_sandbox:
                    code_blocks = re.findall(r"```python\n(.*?)\n```", full_response, re.DOTALL)
                    for code in code_blocks:
                        st.info("🔧 Automatically running Python code...")
                        f = io.StringIO()
                        with contextlib.redirect_stdout(f):
                            try:
                                exec(code, {})
                                output = f.getvalue()
                            except Exception as e:
                                output = f"Error during execution:\n{str(e)}"
                        
                        if output.strip():
                            st.success("📊 Execution Output:")
                            st.code(output)
                            st.session_state.messages.append({
                                "role": "system", 
                                "content": f"System Note: The executed python code resulted in this output:\n{output}"
                            })

            except Exception as e:
                st.error(f"An error occurred: {e}")